version: '3.3'

services:
  ofelia:
    image: mcuadros/ofelia:latest
    depends_on:
      - elsewherr
    command: daemon --docker
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /usr/share/zoneinfo/America/New_York:/etc/localtime
    labels:
      ofelia.job-run.elsewherr.schedule: "0 1 * * *"
      ofelia.job-run.elsewherr.container: "Elsewherr"

  elsewherr:
    build: .
    container_name: Elsewherr
    volumes:
      - /mediabox/Elsewherr:/Elsewherr
      - /usr/share/zoneinfo/America/New_York:/etc/localtime
